import { useNavigate } from "react-router-dom";
import { Button } from "../components/atoms/button/Button.component";
import { CenterLayout } from "../components/layouts/CenterLayout.component";
import { Footer } from "../components/moleculi/Footer.component";
import { Header } from "../components/moleculi/Header.component";
import { LoginForm } from "../components/moleculi/LoginForm.component";

// Generated by https://quicktype.io

export interface LoginInterface {
  email:    string;
  password: string;
}


const Login = () => {
  // Valor global del useContext

  // Uso de useFetch
  // const {data, hasError, isFetching, fetchData} = useFetch<LoginInterface>({url: "https://noderestserver-production-241a.up.railway.app/api/v1/auth/login"})

  // Función para el enrutado
  const navigate = useNavigate();

  return (
    <div className="max-w-screen max-h-screen">
      <Header />
      <CenterLayout width="900">
        <div className="w-full p-4 md:p-12 flex flex-col items-center mt-24">
          <h1 className="text-xl font-bold text-blue-950 mb-6">Login</h1>
          <div className="w-full md:w-1/2 mb-6">
            <LoginForm />
          </div>
          <div className="flex">
            <p className="mr-2">¿No eres usuario?</p> <Button name="Regístrate" width="0" variant="link" onClick={() => navigate("/register")} />
          </div>
        </div>
      </CenterLayout>
      <Footer />
    </div>
  );
};

export default Login;
